#include "get_config.hpp"
#include "config.hpp"
#include "asset.hpp"
#include "types.hpp"
#include "version.hpp"

namespace taiyi { namespace protocol {

    fc::variant_object get_config()
    {
        fc::mutable_variant_object result;
        
#ifdef IS_TEST_NET
        result["IS_TEST_NET"] = true;
#else
        result["IS_TEST_NET"] = false;
#endif
                
        result["YIN_SYMBOL"] = YIN_SYMBOL;
        result["TAIYI_100_PERCENT"] = TAIYI_100_PERCENT;
        result["TAIYI_1_PERCENT"] = TAIYI_1_PERCENT;
        result["TAIYI_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = TAIYI_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
        result["TAIYI_ADDRESS_PREFIX"] = TAIYI_ADDRESS_PREFIX;
        result["TAIYI_BLOCKCHAIN_HARDFORK_VERSION"] = TAIYI_BLOCKCHAIN_HARDFORK_VERSION;
        result["TAIYI_BLOCKCHAIN_VERSION"] = TAIYI_BLOCKCHAIN_VERSION;
        result["TAIYI_BLOCK_INTERVAL"] = TAIYI_BLOCK_INTERVAL;
        result["TAIYI_BLOCKS_PER_DAY"] = TAIYI_BLOCKS_PER_DAY;
        result["TAIYI_BLOCKS_PER_HOUR"] = TAIYI_BLOCKS_PER_HOUR;
        result["TAIYI_BLOCKS_PER_YEAR"] = TAIYI_BLOCKS_PER_YEAR;
        result["TAIYI_CHAIN_ID"] = TAIYI_CHAIN_ID;
        result["TAIYI_CONTENT_REWARD_YANG_PERCENT"] = TAIYI_CONTENT_REWARD_YANG_PERCENT;
        result["TAIYI_CONTENT_REWARD_QI_FUND_PERCENT"] = TAIYI_CONTENT_REWARD_QI_FUND_PERCENT;
        result["TAIYI_CUSTOM_OP_DATA_MAX_LENGTH"] = TAIYI_CUSTOM_OP_DATA_MAX_LENGTH;
        result["TAIYI_CUSTOM_OP_ID_MAX_LENGTH"] = TAIYI_CUSTOM_OP_ID_MAX_LENGTH;
        result["TAIYI_GENESIS_TIME"] = TAIYI_GENESIS_TIME;
        result["TAIYI_HARDFORK_REQUIRED_SIMINGS"] = TAIYI_HARDFORK_REQUIRED_SIMINGS;
        result["TAIYI_INFLATION_NARROWING_PERIOD"] = TAIYI_INFLATION_NARROWING_PERIOD;
        result["TAIYI_INFLATION_RATE_START_PERCENT"] = TAIYI_INFLATION_RATE_START_PERCENT;
        result["TAIYI_INFLATION_RATE_STOP_PERCENT"] = TAIYI_INFLATION_RATE_STOP_PERCENT;
        result["TAIYI_INIT_SIMING_NAME"] = TAIYI_INIT_SIMING_NAME;
        result["TAIYI_INIT_PUBLIC_KEY_STR"] = TAIYI_INIT_PUBLIC_KEY_STR;
#if 0
        // do not expose private key, period.
        // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
        result["TAIYI_INIT_PRIVATE_KEY"] = TAIYI_INIT_PRIVATE_KEY;
#endif
        result["TAIYI_YANG_INIT_SUPPLY"] = TAIYI_YANG_INIT_SUPPLY;
        result["TAIYI_IRREVERSIBLE_THRESHOLD"] = TAIYI_IRREVERSIBLE_THRESHOLD;
        result["TAIYI_MAX_ACCOUNT_CREATION_FEE"] = TAIYI_MAX_ACCOUNT_CREATION_FEE;
        result["TAIYI_MAX_ACCOUNT_NAME_LENGTH"] = TAIYI_MAX_ACCOUNT_NAME_LENGTH;
        result["TAIYI_MAX_ACCOUNT_SIMING_ADORES"] = TAIYI_MAX_ACCOUNT_SIMING_ADORES;
        result["TAIYI_MAX_AUTHORITY_MEMBERSHIP"] = TAIYI_MAX_AUTHORITY_MEMBERSHIP;
        result["TAIYI_MAX_BLOCK_SIZE"] = TAIYI_MAX_BLOCK_SIZE;
        result["TAIYI_SOFT_MAX_BLOCK_SIZE"] = TAIYI_SOFT_MAX_BLOCK_SIZE;
        result["TAIYI_MAX_MEMO_SIZE"] = TAIYI_MAX_MEMO_SIZE;
        result["TAIYI_MAX_SIMINGS"] = TAIYI_MAX_SIMINGS;
        result["TAIYI_MAX_PERMLINK_LENGTH"] = TAIYI_MAX_PERMLINK_LENGTH;
        result["TAIYI_MAX_PROXY_RECURSION_DEPTH"] = TAIYI_MAX_PROXY_RECURSION_DEPTH;
        result["TAIYI_MAX_SATOSHIS"] = TAIYI_MAX_SATOSHIS;
        result["TAIYI_MAX_SIG_CHECK_DEPTH"] = TAIYI_MAX_SIG_CHECK_DEPTH;
        result["TAIYI_MAX_SIG_CHECK_ACCOUNTS"] = TAIYI_MAX_SIG_CHECK_ACCOUNTS;
        result["TAIYI_MAX_TIME_UNTIL_EXPIRATION"] = TAIYI_MAX_TIME_UNTIL_EXPIRATION;
        result["TAIYI_MAX_TRANSACTION_SIZE"] = TAIYI_MAX_TRANSACTION_SIZE;
        result["TAIYI_MAX_UNDO_HISTORY"] = TAIYI_MAX_UNDO_HISTORY;
        result["TAIYI_MAX_WITHDRAW_ROUTES"] = TAIYI_MAX_WITHDRAW_ROUTES;
        result["TAIYI_MAX_SIMING_URL_LENGTH"] = TAIYI_MAX_SIMING_URL_LENGTH;
        result["TAIYI_MIN_ACCOUNT_CREATION_FEE"] = TAIYI_MIN_ACCOUNT_CREATION_FEE;
        result["TAIYI_MIN_ACCOUNT_NAME_LENGTH"] = TAIYI_MIN_ACCOUNT_NAME_LENGTH;
        result["TAIYI_MIN_BLOCK_SIZE_LIMIT"] = TAIYI_MIN_BLOCK_SIZE_LIMIT;
        result["TAIYI_MIN_BLOCK_SIZE"] = TAIYI_MIN_BLOCK_SIZE;
        result["TAIYI_MIN_PERMLINK_LENGTH"] = TAIYI_MIN_PERMLINK_LENGTH;
        result["TAIYI_MIN_REWARD_FUND"] = TAIYI_MIN_REWARD_FUND;
        result["TAIYI_NULL_ACCOUNT"] = TAIYI_NULL_ACCOUNT;
        result["TAIYI_NUM_INIT_SIMINGS"] = TAIYI_NUM_INIT_SIMINGS;
        result["TAIYI_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = TAIYI_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
        result["TAIYI_OWNER_AUTH_RECOVERY_PERIOD"] = TAIYI_OWNER_AUTH_RECOVERY_PERIOD;
        result["TAIYI_OWNER_UPDATE_LIMIT"] = TAIYI_OWNER_UPDATE_LIMIT;
        result["TAIYI_CULTIVATION_REWARD_FUND_NAME"] = TAIYI_CULTIVATION_REWARD_FUND_NAME;
        result["TAIYI_PROXY_TO_SELF_ACCOUNT"] = TAIYI_PROXY_TO_SELF_ACCOUNT;
        result["TAIYI_START_ADORING_BLOCK"] = TAIYI_START_ADORING_BLOCK;
        result["TAIYI_START_QI_BLOCK"] = TAIYI_START_QI_BLOCK;
        result["TAIYI_TEMP_ACCOUNT"] = TAIYI_TEMP_ACCOUNT;
        result["TAIYI_QI_WITHDRAW_INTERVALS"] = TAIYI_QI_WITHDRAW_INTERVALS;
        result["TAIYI_QI_WITHDRAW_INTERVAL_SECONDS"] = TAIYI_QI_WITHDRAW_INTERVAL_SECONDS;
        result["YANG_SYMBOL"] = YANG_SYMBOL;
        result["QI_SYMBOL"] = QI_SYMBOL;
        result["GOLD_SYMBOL"] = GOLD_SYMBOL;
        result["FOOD_SYMBOL"] = FOOD_SYMBOL;
        result["WOOD_SYMBOL"] = WOOD_SYMBOL;
        result["FABRIC_SYMBOL"] = FABRIC_SYMBOL;
        result["HERB_SYMBOL"] = HERB_SYMBOL;
        result["TAIYI_VIRTUAL_SCHEDULE_LAP_LENGTH"] = TAIYI_VIRTUAL_SCHEDULE_LAP_LENGTH;
        result["TAIYI_DELEGATION_RETURN_PERIOD"] = TAIYI_DELEGATION_RETURN_PERIOD;
        result["TAIYI_BLOCK_GENERATION_POSTPONED_TX_LIMIT"] = TAIYI_BLOCK_GENERATION_POSTPONED_TX_LIMIT;
        result["TAIYI_PENDING_TRANSACTION_EXECUTION_LIMIT"] = TAIYI_PENDING_TRANSACTION_EXECUTION_LIMIT;
        result["TAIYI_TREASURY_ACCOUNT"] = TAIYI_TREASURY_ACCOUNT;
        result["TAIYI_DANUO_ACCOUNT"] = TAIYI_DANUO_ACCOUNT;
        result["TAIYI_COMMITTEE_ACCOUNT"] = TAIYI_COMMITTEE_ACCOUNT;
        result["TAIYI_QI_SHARE_PRICE"] = TAIYI_QI_SHARE_PRICE;
        result["TAIYI_GOLD_QI_PRICE"] = TAIYI_GOLD_QI_PRICE;
        result["TAIYI_FOOD_QI_PRICE"] = TAIYI_FOOD_QI_PRICE;
        result["TAIYI_WOOD_QI_PRICE"] = TAIYI_WOOD_QI_PRICE;
        result["TAIYI_FABRIC_QI_PRICE"] = TAIYI_FABRIC_QI_PRICE;
        result["TAIYI_HERB_QI_PRICE"] = TAIYI_HERB_QI_PRICE;
        result["TAIYI_VDAY_BLOCK_NUM"] = TAIYI_VDAY_BLOCK_NUM;
        result["TAIYI_VMONTH_BLOCK_NUM"] = TAIYI_VMONTH_BLOCK_NUM;
        result["TAIYI_NFA_TICK_PERIOD_MAX_BLOCK_NUM"] = TAIYI_NFA_TICK_PERIOD_MAX_BLOCK_NUM;
        result["TAIYI_ACTOR_TICK_PERIOD_MAX_BLOCK_NUM"] = TAIYI_ACTOR_TICK_PERIOD_MAX_BLOCK_NUM;
        result["TAIYI_MIN_CONTRACT_NAME_LENGTH"] = TAIYI_MIN_CONTRACT_NAME_LENGTH;
        result["TAIYI_MAX_CONTRACT_NAME_LENGTH"] = TAIYI_MAX_CONTRACT_NAME_LENGTH;
        result["TAIYI_MIN_NFA_SYMBOL_LENGTH"] = TAIYI_MIN_NFA_SYMBOL_LENGTH;
        result["TAIYI_MAX_NFA_SYMBOL_LENGTH"] = TAIYI_MAX_NFA_SYMBOL_LENGTH;
        result["TAIYI_NFA_INIT_FUNC_NAME"] = TAIYI_NFA_INIT_FUNC_NAME;
        result["TAIYI_ACTOR_TALENT_RULE_INIT_FUNC_NAME"] = TAIYI_ACTOR_TALENT_RULE_INIT_FUNC_NAME;
        result["TAIYI_NFA_SYMBOL_NAME_XINSU_MARK"] = TAIYI_NFA_SYMBOL_NAME_XINSU_MARK;
        result["TAIYI_NFA_SYMBOL_NAME_DEFAULT_ACTOR"] = TAIYI_NFA_SYMBOL_NAME_DEFAULT_ACTOR;
        result["TAIYI_NFA_SYMBOL_NAME_DEFAULT_ZONE"] = TAIYI_NFA_SYMBOL_NAME_DEFAULT_ZONE;

        result["TAIYI_USEMANA_STATE_BYTES_SCALE"] = TAIYI_USEMANA_STATE_BYTES_SCALE;
        result["TAIYI_USEMANA_EXECUTION_SCALE"] = TAIYI_USEMANA_EXECUTION_SCALE;
        result["TAIYI_CONTRACT_USEMANA_REWARD_AUTHOR_PERCENT"] = TAIYI_CONTRACT_USEMANA_REWARD_AUTHOR_PERCENT;
        result["TAIYI_CONTRACT_USEMANA_REWARD_TREASURY_PERCENT"] = TAIYI_CONTRACT_USEMANA_REWARD_TREASURY_PERCENT;
        result["TAIYI_CONTRACT_OBJ_STATE_BYTES"] = TAIYI_CONTRACT_OBJ_STATE_BYTES;
        result["TAIYI_CONTRACT_BIN_OBJ_STATE_BYTES"] = TAIYI_CONTRACT_BIN_OBJ_STATE_BYTES;
        result["TAIYI_NFA_SYMBOL_OBJ_STATE_BYTES"] = TAIYI_NFA_SYMBOL_OBJ_STATE_BYTES;
        result["TAIYI_NFA_OBJ_STATE_BYTES"] = TAIYI_NFA_OBJ_STATE_BYTES;
        result["TAIYI_NFA_MATERIAL_STATE_BYTES"] = TAIYI_NFA_MATERIAL_STATE_BYTES;
        result["TAIYI_ZONE_OBJ_STATE_BYTES"] = TAIYI_ZONE_OBJ_STATE_BYTES;
        result["TAIYI_ACTOR_OBJ_STATE_BYTES"] = TAIYI_ACTOR_OBJ_STATE_BYTES;
        result["TAIYI_MAX_ACTOR_CREATION_FEE"] = TAIYI_MAX_ACTOR_CREATION_FEE;
        result["TAIYI_ACTOR_NAME_LIMIT"] = TAIYI_ACTOR_NAME_LIMIT;
        result["TAIYI_ACTOR_INIT_ATTRIBUTE_AMOUNT"] = TAIYI_ACTOR_INIT_ATTRIBUTE_AMOUNT;
        result["TAIYI_ZONE_NAME_LIMIT"] = TAIYI_ZONE_NAME_LIMIT;
        result["TAIYI_USEMANA_ACTOR_ACTION_SCALE"] = TAIYI_USEMANA_ACTOR_ACTION_SCALE;
        result["TAIYI_CULTIVATION_PREPARE_MIN_TIME_BLOCK_NUM"] = TAIYI_CULTIVATION_PREPARE_MIN_TIME_BLOCK_NUM;
        result["TAIYI_CULTIVATION_MAX_TIME_BLOCK_NUM"] = TAIYI_CULTIVATION_MAX_TIME_BLOCK_NUM;

        return result;
    }

} } // taiyi::protocol
