#include "get_config.hpp"
#include "config.hpp"
#include "asset.hpp"
#include "types.hpp"
#include "version.hpp"

namespace taiyi { namespace protocol {

    fc::variant_object get_config()
    {
        fc::mutable_variant_object result;
        
#ifdef IS_TEST_NET
        result["IS_TEST_NET"] = true;
#else
        result["IS_TEST_NET"] = false;
#endif
                
        result["YIN_SYMBOL"] = YIN_SYMBOL;
        result["TAIYI_100_PERCENT"] = TAIYI_100_PERCENT;
        result["TAIYI_1_PERCENT"] = TAIYI_1_PERCENT;
        result["TAIYI_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD"] = TAIYI_ACCOUNT_RECOVERY_REQUEST_EXPIRATION_PERIOD;
        result["TAIYI_ADDRESS_PREFIX"] = TAIYI_ADDRESS_PREFIX;
        result["TAIYI_BLOCKCHAIN_PRECISION"] = TAIYI_BLOCKCHAIN_PRECISION;
        result["TAIYI_BLOCKCHAIN_PRECISION_DIGITS"] = TAIYI_BLOCKCHAIN_PRECISION_DIGITS;
        result["TAIYI_BLOCKCHAIN_HARDFORK_VERSION"] = TAIYI_BLOCKCHAIN_HARDFORK_VERSION;
        result["TAIYI_BLOCKCHAIN_VERSION"] = TAIYI_BLOCKCHAIN_VERSION;
        result["TAIYI_BLOCK_INTERVAL"] = TAIYI_BLOCK_INTERVAL;
        result["TAIYI_BLOCKS_PER_DAY"] = TAIYI_BLOCKS_PER_DAY;
        result["TAIYI_BLOCKS_PER_HOUR"] = TAIYI_BLOCKS_PER_HOUR;
        result["TAIYI_BLOCKS_PER_YEAR"] = TAIYI_BLOCKS_PER_YEAR;
        result["TAIYI_CHAIN_ID"] = TAIYI_CHAIN_ID;
        result["TAIYI_CONTENT_REWARD_YANG_PERCENT"] = TAIYI_CONTENT_REWARD_YANG_PERCENT;
        result["TAIYI_CONTENT_REWARD_QI_FUND_PERCENT"] = TAIYI_CONTENT_REWARD_QI_FUND_PERCENT;
        result["TAIYI_CUSTOM_OP_DATA_MAX_LENGTH"] = TAIYI_CUSTOM_OP_DATA_MAX_LENGTH;
        result["TAIYI_CUSTOM_OP_ID_MAX_LENGTH"] = TAIYI_CUSTOM_OP_ID_MAX_LENGTH;
        result["TAIYI_GENESIS_TIME"] = TAIYI_GENESIS_TIME;
        result["TAIYI_HARDFORK_REQUIRED_SIMINGS"] = TAIYI_HARDFORK_REQUIRED_SIMINGS;
        result["TAIYI_INFLATION_NARROWING_PERIOD"] = TAIYI_INFLATION_NARROWING_PERIOD;
        result["TAIYI_INFLATION_RATE_START_PERCENT"] = TAIYI_INFLATION_RATE_START_PERCENT;
        result["TAIYI_INFLATION_RATE_STOP_PERCENT"] = TAIYI_INFLATION_RATE_STOP_PERCENT;
        result["TAIYI_INIT_SIMING_NAME"] = TAIYI_INIT_SIMING_NAME;
        result["TAIYI_INIT_PUBLIC_KEY_STR"] = TAIYI_INIT_PUBLIC_KEY_STR;
#if 0
        // do not expose private key, period.
        // we need this line present but inactivated so CI check for all constants in config.hpp doesn't complain.
        result["TAIYI_INIT_PRIVATE_KEY"] = TAIYI_INIT_PRIVATE_KEY;
#endif
        result["TAIYI_YANG_INIT_SUPPLY"] = TAIYI_YANG_INIT_SUPPLY;
        result["TAIYI_IRREVERSIBLE_THRESHOLD"] = TAIYI_IRREVERSIBLE_THRESHOLD;
        result["TAIYI_MAX_ACCOUNT_CREATION_FEE"] = TAIYI_MAX_ACCOUNT_CREATION_FEE;
        result["TAIYI_MAX_ACCOUNT_NAME_LENGTH"] = TAIYI_MAX_ACCOUNT_NAME_LENGTH;
        result["TAIYI_MAX_ACCOUNT_SIMING_ADORES"] = TAIYI_MAX_ACCOUNT_SIMING_ADORES;
        result["TAIYI_MAX_AUTHORITY_MEMBERSHIP"] = TAIYI_MAX_AUTHORITY_MEMBERSHIP;
        result["TAIYI_MAX_BLOCK_SIZE"] = TAIYI_MAX_BLOCK_SIZE;
        result["TAIYI_SOFT_MAX_BLOCK_SIZE"] = TAIYI_SOFT_MAX_BLOCK_SIZE;
        result["TAIYI_MAX_MEMO_SIZE"] = TAIYI_MAX_MEMO_SIZE;
        result["TAIYI_MAX_SIMINGS"] = TAIYI_MAX_SIMINGS;
        result["TAIYI_MAX_PERMLINK_LENGTH"] = TAIYI_MAX_PERMLINK_LENGTH;
        result["TAIYI_MAX_PROXY_RECURSION_DEPTH"] = TAIYI_MAX_PROXY_RECURSION_DEPTH;
        result["TAIYI_MAX_SATOSHIS"] = TAIYI_MAX_SATOSHIS;
        result["TAIYI_MAX_SIG_CHECK_DEPTH"] = TAIYI_MAX_SIG_CHECK_DEPTH;
        result["TAIYI_MAX_SIG_CHECK_ACCOUNTS"] = TAIYI_MAX_SIG_CHECK_ACCOUNTS;
        result["TAIYI_MAX_TIME_UNTIL_EXPIRATION"] = TAIYI_MAX_TIME_UNTIL_EXPIRATION;
        result["TAIYI_MAX_TRANSACTION_SIZE"] = TAIYI_MAX_TRANSACTION_SIZE;
        result["TAIYI_MAX_UNDO_HISTORY"] = TAIYI_MAX_UNDO_HISTORY;
        result["TAIYI_MAX_WITHDRAW_ROUTES"] = TAIYI_MAX_WITHDRAW_ROUTES;
        result["TAIYI_MAX_SIMING_URL_LENGTH"] = TAIYI_MAX_SIMING_URL_LENGTH;
        result["TAIYI_MIN_ACCOUNT_CREATION_FEE"] = TAIYI_MIN_ACCOUNT_CREATION_FEE;
        result["TAIYI_MIN_ACCOUNT_NAME_LENGTH"] = TAIYI_MIN_ACCOUNT_NAME_LENGTH;
        result["TAIYI_MIN_BLOCK_SIZE_LIMIT"] = TAIYI_MIN_BLOCK_SIZE_LIMIT;
        result["TAIYI_MIN_BLOCK_SIZE"] = TAIYI_MIN_BLOCK_SIZE;
        result["TAIYI_MIN_PERMLINK_LENGTH"] = TAIYI_MIN_PERMLINK_LENGTH;
        result["TAIYI_MIN_REWARD_FUND"] = TAIYI_MIN_REWARD_FUND;
        result["TAIYI_NULL_ACCOUNT"] = TAIYI_NULL_ACCOUNT;
        result["TAIYI_NUM_INIT_SIMINGS"] = TAIYI_NUM_INIT_SIMINGS;
        result["TAIYI_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM"] = TAIYI_OWNER_AUTH_HISTORY_TRACKING_START_BLOCK_NUM;
        result["TAIYI_OWNER_AUTH_RECOVERY_PERIOD"] = TAIYI_OWNER_AUTH_RECOVERY_PERIOD;
        result["TAIYI_OWNER_UPDATE_LIMIT"] = TAIYI_OWNER_UPDATE_LIMIT;
        result["TAIYI_CULTIVATION_REWARD_FUND_NAME"] = TAIYI_CULTIVATION_REWARD_FUND_NAME;
        result["TAIYI_PROXY_TO_SELF_ACCOUNT"] = TAIYI_PROXY_TO_SELF_ACCOUNT;
        result["TAIYI_ROOT_POST_PARENT"] = TAIYI_ROOT_POST_PARENT;
        result["TAIYI_START_MINER_ADORING_BLOCK"] = TAIYI_START_MINER_ADORING_BLOCK;
        result["TAIYI_START_QI_BLOCK"] = TAIYI_START_QI_BLOCK;
        result["TAIYI_TEMP_ACCOUNT"] = TAIYI_TEMP_ACCOUNT;
        result["TAIYI_QI_WITHDRAW_INTERVALS"] = TAIYI_QI_WITHDRAW_INTERVALS;
        result["TAIYI_QI_WITHDRAW_INTERVAL_SECONDS"] = TAIYI_QI_WITHDRAW_INTERVAL_SECONDS;
        result["TAIYI_MANA_REGENERATION_SECONDS"] = TAIYI_MANA_REGENERATION_SECONDS;
        result["YANG_SYMBOL"] = YANG_SYMBOL;
        result["QI_SYMBOL"] = QI_SYMBOL;
        result["TAIYI_VIRTUAL_SCHEDULE_LAP_LENGTH"] = TAIYI_VIRTUAL_SCHEDULE_LAP_LENGTH;
        result["TAIYI_DELEGATION_RETURN_PERIOD"] = TAIYI_DELEGATION_RETURN_PERIOD;
        result["TAIYI_RD_MIN_DECAY_BITS"] = TAIYI_RD_MIN_DECAY_BITS;
        result["TAIYI_RD_MAX_DECAY_BITS"] = TAIYI_RD_MAX_DECAY_BITS;
        result["TAIYI_RD_DECAY_DENOM_SHIFT"] = TAIYI_RD_DECAY_DENOM_SHIFT;
        result["TAIYI_RD_MAX_POOL_BITS"] = TAIYI_RD_MAX_POOL_BITS;
        result["TAIYI_RD_MAX_BUDGET_1"] = TAIYI_RD_MAX_BUDGET_1;
        result["TAIYI_RD_MAX_BUDGET_2"] = TAIYI_RD_MAX_BUDGET_2;
        result["TAIYI_RD_MAX_BUDGET_3"] = TAIYI_RD_MAX_BUDGET_3;
        result["TAIYI_RD_MAX_BUDGET"] = TAIYI_RD_MAX_BUDGET;
        result["TAIYI_RD_MIN_DECAY"] = TAIYI_RD_MIN_DECAY;
        result["TAIYI_RD_MIN_BUDGET"] = TAIYI_RD_MIN_BUDGET;
        result["TAIYI_RD_MAX_DECAY"] = TAIYI_RD_MAX_DECAY;
        result["TAIYI_BLOCK_GENERATION_POSTPONED_TX_LIMIT"] = TAIYI_BLOCK_GENERATION_POSTPONED_TX_LIMIT;
        result["TAIYI_PENDING_TRANSACTION_EXECUTION_LIMIT"] = TAIYI_PENDING_TRANSACTION_EXECUTION_LIMIT;
        result["TAIYI_TREASURY_ACCOUNT"] = TAIYI_TREASURY_ACCOUNT;
        
        return result;
    }

} } // taiyi::protocol
